AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  scottcraigwebsite

  Sample SAM Template for scottcraigwebsite

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SiteFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: site/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        Site:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SiteApi:
    Description: "API Gateway endpoint URL for Prod stage for the Site function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  SiteFunction:
    Description: "Site Lambda Function ARN"
    Value: !GetAtt SiteFunction.Arn
  SiteFunctionIamRole:
    Description: "Implicit IAM Role created for Site function"
    Value: !GetAtt SiteFunctionRole.Arn
